### ISSUE TITLE
Undecryptable block causes runtime crash 

### ISSUE THREAD

**Issue by peekpt** [drriguz/encryptions#9]
```
I/flutter ( 6655): payload to decrypt: [22, 5E, A9, 4F, 44, F2, 11, 00, 54, 69, 8A, 13, 95, 5F, 49, C1]
E/AndroidRuntime( 6655): FATAL EXCEPTION: Thread-9
E/AndroidRuntime( 6655): Process: com.xxxx.xxxxxxx PID: 6655
E/AndroidRuntime( 6655): java.lang.NullPointerException: println needs a message
E/AndroidRuntime( 6655): 	at android.util.Log.println_native(Native Method)
E/AndroidRuntime( 6655): 	at android.util.Log.e(Log.java:253)
E/AndroidRuntime( 6655): 	at com.riguz.encryptions.FlutterCallExecutor.execute(FlutterCallExecutor.java:79)
E/AndroidRuntime( 6655): 	at com.riguz.encryptions.FlutterCallExecutor.access$000(FlutterCallExecutor.java:18)
E/AndroidRuntime( 6655): 	at com.riguz.encryptions.FlutterCallExecutor$1.run(FlutterCallExecutor.java:51)
E/AndroidRuntime( 6655): 	at java.lang.Thread.run(Thread.java:923)
I/Process ( 6655): Sending signal. PID: 6655 SIG: 9

```
It's crashing when it can't decrypt, maybe throw an Exception here will be the solution, a callback  onError(e): parameter in the method

edit:
```
I/flutter (30791): key Uint8List- [65, 67, 66, 50, 54, 55, 65, 67, 54, 65, 57, 68, 53, 54, 54, 65]
I/flutter (30791): iv Uint8List- [54, 65, 57, 68, 53, 54, 54, 65, 65, 67, 66, 50, 54, 55, 65, 67]

( not correctly encrypted) 
I/flutter (30791): data Uint8List- [211, 188, 12, 116, 12, 187, 37, 157, 34, 94, 173, 79, 68, 112, 17, 0]

```

```
AES aes = AES.ofCBC(key, iv, PaddingScheme.PKCS5Padding);
Uint8List decrypted = await aes.decrypt(data); <-crashes here
```

For sure the input data is malformed but there must be a way for not crashing the whole app.

**Comment by drriguz** [comment]
Actually there's error handling in android side, however the error message is not carefully handled when logging. A fixed version has been published, please try it!

**Comment by peekpt** [comment]
it catches the exception now! thanks a lot! phew!
PlatformException(FLUTTER_CALL_ERROR, invocation error, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, null)
